default: &default
  adapter: solid_cable
  silence_polling: true
  polling_interval: 0.5.seconds
  message_retention: 10.seconds
  connects_to:
    database:
      writing: cable

development:
  adapter: async

test:
  adapter: test

production:
  <<: *default
