default: &default
  adapter: solid_cable
  silence_polling: true
  polling_interval: 1.second
  keep_messages_around_for: 10.seconds
  
development:
  <<: *default

test:
  adapter: inline

staging:
  <<: *default

production:
  <<: *default
