default: &default
  adapter: solid_cable
  silence_polling: true
  polling_interval: 1
  keep_messages_around_for: 60.minutes
  
development:
  <<: *default

test:
  adapter: inline

staging:
  <<: *default

production:
  <<: *default
