default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  idle_timeout: 0
  database: db/<%= Rails.env %>/data.sqlite3

development:
  <<: *default
  database: db/development/data.sqlite3

test:
  <<: *default

production:
  <<: *default
