primary_default: &primary_default
  url: <%= ENV.fetch("SHIPYRD_DATABASE_URL") { "#{ENV['SHIPYRD_DATABASE_HOST']}/shipyrd_primary" } %>

queue_default: &queue_default
  url: <%= ENV.fetch("SHIPYRD_QUEUE_DATABASE_URL") { "#{ENV['SHIPYRD_DATABASE_HOST']}/shipyrd_queue" } %>
  migrations_paths: db/queue_migrate

cable_default: &cable_default
  url: <%= ENV.fetch("SHIPYRD_CABLE_DATABASE_URL") { "#{ENV['SHIPYRD_DATABASE_HOST']}/shipyrd_cable" } %>
  migrations_paths: db/cable_migrate

development:
  primary:
    <<: *primary_default
  queue:
    <<: *queue_default
  cable:
    <<: *cable_default

test:
  primary:
    <<: *primary_default
  queue:
    <<: *queue_default
  cable:
    <<: *cable_default

production:
  primary:
    <<: *primary_default
  queue:
    <<: *queue_default
  cable:
    <<: *cable_default
