primary_default: &primary_default
  adapter: mysql2
  url: <%= ENV["SHIPYRD_DATABASE_URL"] %>

queue_default: &queue_default
  adapter: mysql2
  url: <%= ENV["SHIPYRD_QUEUE_DATABASE_URL"] %>
  migrations_paths: db/queue_migrate

cable_default: &cable_default
  adapter: mysql2
  url: <%= ENV["SHIPYRD_CABLE_DATABASE_URL"] %>
  migrations_paths: db/cable_migrate

development:
  primary:
    <<: *primary_default
  queue:
    <<: *queue_default
  cable:
    <<: *cable_default

test:
  adapter: mysql2
  url: <%= ENV["SHIPYRD_DATABASE_URL"] %>

production:
  primary:
    <<: *primary_default
  queue:
    <<: *queue_default
  cable:
    <<: *cable_default
