primary_default: &primary_default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  idle_timeout: 0
  database: db/<%= Rails.env %>/data.sqlite3

queue_default: &queue_default
  adapter: sqlite3
  database: db/<%= Rails.env %>/queue.sqlite3
  migrations_paths: db/queue_migrate

cable_default: &cable_default
  adapter: sqlite3
  database: db/<%= Rails.env %>/cable.sqlite3
  migrations_paths: db/cable_migrate

development:
  primary:
    <<: *primary_default
  queue:
    <<: *queue_default
  cable:
    <<: *cable_default

test:
  primary:
    <<: *primary_default
  queue:
    <<: *queue_default
  cable:
    <<: *cable_default

production:
  primary:
    <<: *primary_default
  queue:
    <<: *queue_default
  cable:
    <<: *cable_default
