name: Test

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SHIPYRD_DATABASE_HOST: mysql2://root:root@localhost:3306
      SHIPYRD_SECRET_KEY_BASE: 823676323609aa7429ad867c12e77d1a4e2af30c764d51ad9db913efa4cf27742cc654fcfe7d9031d2d46c4be57f93bce05b9f81aefa65fad58999c0c2aaba71
      SHIPYRD_ENCRYPTION_PRIMARY_KEY: 823676323609aa7429ad867c12e77d1a4e2af3
      SHIPYRD_ENCRYPTION_DETERMINISTIC_KEY: 823676323609aa7429ad867c12e77d1a4e2af3
      SHIPYRD_ENCRYPTION_KEY_DERIVATION_SALT: 823676323609aa7429ad867c12e77d1a4e2af3

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: shipyrd_test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install mysql client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - run: bundle exec rails db:prepare
      - run: bundle exec rails test
      - run: bundle exec rails test:system
      - run: bundle exec standardrb
      - run: bundle exec brakeman
      - run: bin/audit
